plugins {
	id 'java'
}

group = 'de.reticulum.sarcinae'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

//jar {
//  enabled = true
//}

dependencies {
	implementation project(':backend')
}

allprojects {
	apply plugin: 'java'
	apply plugin: 'idea'

	idea {
		module {
			downloadJavadoc = true
			downloadSources = true
		}
	}

	test {
		useJUnitPlatform()
	}

	repositories {
		mavenLocal()
		mavenCentral()
	}

	dependencies {
		implementation "org.projectlombok:lombok:${lombokVersion}"
		annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

		testRuntimeOnly "org.junit.platform:junit-platform-launcher:${junitVersion}"
		testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"
	}

	configurations {
		compileOnly {
			extendsFrom annotationProcessor
		}
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
