plugins {
  id 'java'
  id 'org.springframework.boot' version "${springBootVersion}"
}

bootJar {
  archiveFileName = 'app.jar'
}

dependencies {
  implementation project(':domain:api')
  implementation project(':domain:usecase')

  runtimeOnly project(':core')
  rootProject.project(':domain:port').subprojects.each { portProject ->
    runtimeOnly project(portProject.path)
  }
  rootProject.project(':adapter').subprojects.each { adapterProject ->
    runtimeOnly project(adapterProject.path)
  }

  implementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
  implementation "org.springframework.boot:spring-boot-starter-security:${springBootVersion}"
  implementation "org.springframework.boot:spring-boot-starter-actuator:${springBootVersion}"
  implementation "org.mapstruct:mapstruct:${mapstructVersion}"

  annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

  testImplementation project(':adapter:persistence')
  testImplementation "org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}"
  testImplementation "org.springframework.security:spring-security-test:${springSecurityVersion}"
  testImplementation "org.springframework.boot:spring-boot-starter-webmvc-test:${springBootVersion}"

  testImplementation "org.testcontainers:mariadb:${testcontainersVersion}"
  testImplementation "org.flywaydb:flyway-core:${flywayVersion}"
  testRuntimeOnly "org.mariadb.jdbc:mariadb-java-client:${maiadbClientVersion}"
}
